name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Required for pushing compiled CSS
  pull-requests: read  # Good practice to explicitly define

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
      fail-fast: false  # Continue with other versions if one fails

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
        with:
          fetch-depth: 0  # Full history for better versioning

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Enable npm caching

      - name: Install Dependencies
        run: npm ci  # More reliable than npm install for CI

      - name: Build Project
        run: npm run build --if-present

      - name: Run Tests
        run: npm test
        env:
          CI: true
          NODE_ENV: test

  compile-scss:
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Only run on main branch pushes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci
          npm install -D sass \
                        grunt \
                        grunt-cli \
                        grunt-contrib-sass \
                        grunt-autoprefixer \
                        grunt-sass \
                        sass-loader

      - name: Compile SCSS to CSS
        run: |
          npx grunt sass --force
          npx grunt autoprefixer --force

      - name: Check for CSS Changes
        id: css-changes
        run: |
          git add ./css/theme/cy.css
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and Push CSS
        if: steps.css-changes.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Using built-in token instead of PAT
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: compile SCSS to CSS [skip ci]"
          git push
